### ISSUE TITLE
can't see notes on browsers with light mode

### ISSUE THREAD

**Issue by nilaachandra** [TusharSoni014/beautiful-notes#1]
![Screenshot_2024-09-05-21-40-33-99_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/user-attachments/assets/5201274f-3ee5-4552-a8c6-2067fd4907d7)

on browsers with light mode the notes aren't visible due to the text color.

**Comment by TusharSoni014** [comment]
fixed, closing
